stages:
  - build
  - release

build_extension:
  stage: build
  image: node:22-alpine
  script:
    - npm install
    - npm run compile
    - npx @vscode/vsce package
  artifacts:
    paths:
      - vscode-copilot-code-review-*.vsix

release:
  stage: release
  script:
    - |
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
      --form "name=Release $CI_COMMIT_TAG" \
      --form "tag_name=$CI_COMMIT_TAG" \
      --form "description=Automated release for $CI_COMMIT_TAG" \
      --form "assets[links][][name]=VSIX File" \
      --form "assets[links][][url]=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/vscode-copilot-code-review-0.2.1.vsix" \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - tags
